# .github/workflows/flutter-web-deploy.yml
name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install a recent Flutter that includes Dart >= 3.9
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'   # or newer stable that your project supports
          channel: 'stable'

      - name: Show versions
        run: |
          flutter --version
          dart --version

      - name: Enable web
        run: flutter config --enable-web

      - name: Pub get
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --web-renderer html --base-href /tygabsi/

      - name: SPA 404 fallback
        run: cp build/web/index.html build/web/404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
